# Generated by Django 4.1.3 on 2022-12-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.TextField(blank=True, max_length=100, null=True, verbose_name="client's complete name")),
                ('contact', models.TextField(blank=True, max_length=20, null=True)),
                ('company', models.TextField(blank=True, max_length=50, null=True)),
                ('inquiry_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-inquiry_at'],
            },
        ),
    ]
