# Generated by Django 4.1.3 on 2022-12-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="client's complete name"),
        ),
    ]
