# Generated by Django 4.1.3 on 2022-12-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_company_alter_inquiry_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
