# Generated by Django 4.1.3 on 2022-12-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_user_inquiry_status_inquiry_updated_at_inquiry_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TestUser',
        ),
    ]
