# Generated by Django 4.1.3 on 2022-12-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_alter_testuser_options_remove_testuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='staff',
        ),
    ]
